import os


def main():
    os.system('cls')
    print("wordlist_master v1.2 by marilyn_capwn")
    print("MafiaSec Cybersecurity")
    print("https://mafiasec.net")
    print("")
    print("Options:")
    print("1. Generate New Wordlist")
    print("2. Exit")
    print("")
    print("Please select an option by entering a number.")
    print("")
    choiceinput=input("")
    if choiceinput == "1":
        listcreate()
    if choiceinput == "2":
        exit()

def listcreate():
    os.system('cls')
    print("Important Advice: wordlist_master will take your input and store the original as well as variants of it in the wordlist file.\r\n \r\nWe recommend that you begin by entering the target's First Name, Last Name, Any Pets' Names, \r\nNames of Important Relatives, Birthplace, Location, Nicknames, Idols, Favorite Movies, Favorite Characters, etc.")
    print("")
    print("Add words line-by-line.")
    print("")
    wordinput = input("")
    wordinputstr=str(wordinput)
    winstr=wordinputstr #renaming for sake of brevity


    #spam because dumb programmer huehuehue
    winstr53 = (winstr + "1953\r\n")
    winstr54 = (winstr + "1954\r\n")
    winstr55 = (winstr + "1955\r\n")
    winstr56 = (winstr + "1956\r\n")
    winstr57 = (winstr + "1957\r\n")
    winstr58 = (winstr + "1958\r\n")
    winstr59 = (winstr + "1959\r\n")
    winstr60 = (winstr + "1960\r\n")
    winstr61 = (winstr + "1961\r\n")
    winstr62 = (winstr + "1962\r\n")
    winstr63 = (winstr + "1963\r\n")
    winstr64 = (winstr + "1964\r\n")
    winstr65 = (winstr + "1965\r\n")
    winstr66 = (winstr + "1966\r\n")
    winstr67 = (winstr + "1967\r\n")
    winstr68 = (winstr + "1968\r\n")
    winstr69 = (winstr + "1969\r\n")
    winstr70 = (winstr + "1970\r\n")
    winstr71 = (winstr + "1971\r\n")
    winstr72 = (winstr + "1972\r\n")
    winstr73 = (winstr + "1973\r\n")
    winstr74 = (winstr + "1974\r\n")
    winstr75 = (winstr + "1975\r\n")
    winstr76 = (winstr + "1976\r\n")
    winstr77 = (winstr + "1977\r\n")
    winstr78 = (winstr + "1978\r\n")
    winstr79 = (winstr + "1979\r\n")
    winstr80 = (winstr + "1980\r\n")
    winstr81 = (winstr + "1981\r\n")
    winstr82 = (winstr + "1982\r\n")
    winstr83 = (winstr + "1983\r\n")
    winstr84 = (winstr + "1984\r\n")
    winstr85 = (winstr + "1985\r\n")
    winstr86 = (winstr + "1986\r\n")
    winstr87 = (winstr + "1987\r\n")
    winstr88 = (winstr + "1988\r\n")
    winstr89 = (winstr + "1989\r\n")
    winstr90 = (winstr + "1990\r\n")
    winstr91 = (winstr + "1991\r\n")
    winstr92 = (winstr + "1992\r\n")
    winstr93 = (winstr + "1993\r\n")
    winstr94 = (winstr + "1994\r\n")
    winstr95 = (winstr + "1995\r\n")
    winstr96 = (winstr + "1996\r\n")
    winstr97 = (winstr + "1997\r\n")
    winstr98 = (winstr + "1998\r\n")
    winstr99 = (winstr + "1999\r\n")
    #spam because dumb programmer huehuehue
    winstr153 = (winstr + "53\r\n")
    winstr154 = (winstr + "54\r\n")
    winstr155 = (winstr + "55\r\n")
    winstr156 = (winstr + "56\r\n")
    winstr157 = (winstr + "57\r\n")
    winstr158 = (winstr + "58\r\n")
    winstr159 = (winstr + "59\r\n")
    winstr160 = (winstr + "60\r\n")
    winstr161 = (winstr + "61\r\n")
    winstr162 = (winstr + "62\r\n")
    winstr163 = (winstr + "63\r\n")
    winstr164 = (winstr + "64\r\n")
    winstr165 = (winstr + "65\r\n")
    winstr166 = (winstr + "66\r\n")
    winstr167 = (winstr + "67\r\n")
    winstr168 = (winstr + "68\r\n")
    winstr169 = (winstr + "69\r\n")
    winstr170 = (winstr + "70\r\n")
    winstr171 = (winstr + "71\r\n")
    winstr172 = (winstr + "72\r\n")
    winstr173 = (winstr + "73\r\n")
    winstr174 = (winstr + "74\r\n")
    winstr175 = (winstr + "75\r\n")
    winstr176 = (winstr + "76\r\n")
    winstr177 = (winstr + "77\r\n")
    winstr178 = (winstr + "78\r\n")
    winstr179 = (winstr + "79\r\n")
    winstr180 = (winstr + "80\r\n")
    winstr181 = (winstr + "81\r\n")
    winstr182 = (winstr + "82\r\n")
    winstr183 = (winstr + "83\r\n")
    winstr184 = (winstr + "84\r\n")
    winstr185 = (winstr + "85\r\n")
    winstr186 = (winstr + "86\r\n")
    winstr187 = (winstr + "87\r\n")
    winstr188 = (winstr + "88\r\n")
    winstr189 = (winstr + "89\r\n")
    winstr190 = (winstr + "90\r\n")
    winstr191 = (winstr + "91\r\n")
    winstr192 = (winstr + "92\r\n")
    winstr193 = (winstr + "93\r\n")
    winstr194 = (winstr + "94\r\n")
    winstr195 = (winstr + "95\r\n")
    winstr196 = (winstr + "96\r\n")
    winstr197 = (winstr + "97\r\n")
    winstr198 = (winstr + "98\r\n")
    winstr199 = (winstr + "99\r\n")

#writing real string to list
    file = open("wordlist_test.txt", "w+")
    file.write(wordinputstr+"\n")
    file.close()

#writing variations of string to list
    file = open("wordlist_test.txt", "a")
    file.write(winstr53)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr54)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr55)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr56)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr57)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr58)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr59)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr60)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr61)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr61)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr62)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr63)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr64)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr65)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr66)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr67)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr68)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr69)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr70)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr71)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr72)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr73)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr74)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr75)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr76)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr77)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr78)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr79)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr80)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr81)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr82)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr83)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr84)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr85)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr86)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr87)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr88)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr89)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr90)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr91)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr92)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr93)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr94)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr95)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr96)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr97)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr98)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr99)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr153)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr154)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr155)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr156)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr157)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr158)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr159)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr160)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr161)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr161)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr162)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr163)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr164)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr165)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr166)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr167)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr168)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr169)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr170)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr171)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr172)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr173)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr174)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr175)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr176)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr177)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr178)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr179)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr180)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr181)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr182)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr183)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr184)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr185)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr186)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr187)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr188)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr189)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr190)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr191)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr192)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr193)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr194)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr195)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr196)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr197)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr198)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr199)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"12\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"11\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"69\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"01\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"22\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"13\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"99\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"10\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"23\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"21\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"00\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"77\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"88\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"33\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"19\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"1\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"2\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"3\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"4\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"5\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"6\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"7\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"8\r\n")
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"9\r\n")1
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr+"10\r\n")
    file.close()

    os.system('cls')
    print("Great, WordlistMaker has it's first word. Type '1' to continue or '2' to stop.")
    choice=input("")
    if choice == "1":
        listappend()
    if choice == "2":
        main()


def listappend():
    os.system('cls')
    print("")
    print("Add words line-by-line.")
    print("")
    wordinput = input("")
    wordinputstr=str(wordinput)

    winstr=wordinputstr #renaming for sake of brevity

    #spam because dumb programmer huehuehue
    winstr53 = (winstr + "1953\r\n")
    winstr54 = (winstr + "1954\r\n")
    winstr55 = (winstr + "1955\r\n")
    winstr56 = (winstr + "1956\r\n")
    winstr57 = (winstr + "1957\r\n")
    winstr58 = (winstr + "1958\r\n")
    winstr59 = (winstr + "1959\r\n")
    winstr60 = (winstr + "1960\r\n")
    winstr61 = (winstr + "1961\r\n")
    winstr62 = (winstr + "1962\r\n")
    winstr63 = (winstr + "1963\r\n")
    winstr64 = (winstr + "1964\r\n")
    winstr65 = (winstr + "1965\r\n")
    winstr66 = (winstr + "1966\r\n")
    winstr67 = (winstr + "1967\r\n")
    winstr68 = (winstr + "1968\r\n")
    winstr69 = (winstr + "1969\r\n")
    winstr70 = (winstr + "1970\r\n")
    winstr71 = (winstr + "1971\r\n")
    winstr72 = (winstr + "1972\r\n")
    winstr73 = (winstr + "1973\r\n")
    winstr74 = (winstr + "1974\r\n")
    winstr75 = (winstr + "1975\r\n")
    winstr76 = (winstr + "1976\r\n")
    winstr77 = (winstr + "1977\r\n")
    winstr78 = (winstr + "1978\r\n")
    winstr79 = (winstr + "1979\r\n")
    winstr80 = (winstr + "1980\r\n")
    winstr81 = (winstr + "1981\r\n")
    winstr82 = (winstr + "1982\r\n")
    winstr83 = (winstr + "1983\r\n")
    winstr84 = (winstr + "1984\r\n")
    winstr85 = (winstr + "1985\r\n")
    winstr86 = (winstr + "1986\r\n")
    winstr87 = (winstr + "1987\r\n")
    winstr88 = (winstr + "1988\r\n")
    winstr89 = (winstr + "1989\r\n")
    winstr90 = (winstr + "1990\r\n")
    winstr91 = (winstr + "1991\r\n")
    winstr92 = (winstr + "1992\r\n")
    winstr93 = (winstr + "1993\r\n")
    winstr94 = (winstr + "1994\r\n")
    winstr95 = (winstr + "1995\r\n")
    winstr96 = (winstr + "1996\r\n")
    winstr97 = (winstr + "1997\r\n")
    winstr98 = (winstr + "1998\r\n")
    winstr99 = (winstr + "1999\r\n")
    #spam because dumb programmer huehuehue
    winstr153 = (winstr + "53\r\n")
    winstr154 = (winstr + "54\r\n")
    winstr155 = (winstr + "55\r\n")
    winstr156 = (winstr + "56\r\n")
    winstr157 = (winstr + "57\r\n")
    winstr158 = (winstr + "58\r\n")
    winstr159 = (winstr + "59\r\n")
    winstr160 = (winstr + "60\r\n")
    winstr161 = (winstr + "61\r\n")
    winstr162 = (winstr + "62\r\n")
    winstr163 = (winstr + "63\r\n")
    winstr164 = (winstr + "64\r\n")
    winstr165 = (winstr + "65\r\n")
    winstr166 = (winstr + "66\r\n")
    winstr167 = (winstr + "67\r\n")
    winstr168 = (winstr + "68\r\n")
    winstr169 = (winstr + "69\r\n")
    winstr170 = (winstr + "70\r\n")
    winstr171 = (winstr + "71\r\n")
    winstr172 = (winstr + "72\r\n")
    winstr173 = (winstr + "73\r\n")
    winstr174 = (winstr + "74\r\n")
    winstr175 = (winstr + "75\r\n")
    winstr176 = (winstr + "76\r\n")
    winstr177 = (winstr + "77\r\n")
    winstr178 = (winstr + "78\r\n")
    winstr179 = (winstr + "79\r\n")
    winstr180 = (winstr + "80\r\n")
    winstr181 = (winstr + "81\r\n")
    winstr182 = (winstr + "82\r\n")
    winstr183 = (winstr + "83\r\n")
    winstr184 = (winstr + "84\r\n")
    winstr185 = (winstr + "85\r\n")
    winstr186 = (winstr + "86\r\n")
    winstr187 = (winstr + "87\r\n")
    winstr188 = (winstr + "88\r\n")
    winstr189 = (winstr + "89\r\n")
    winstr190 = (winstr + "90\r\n")
    winstr191 = (winstr + "91\r\n")
    winstr192 = (winstr + "92\r\n")
    winstr193 = (winstr + "93\r\n")
    winstr194 = (winstr + "94\r\n")
    winstr195 = (winstr + "95\r\n")
    winstr196 = (winstr + "96\r\n")
    winstr197 = (winstr + "97\r\n")
    winstr198 = (winstr + "98\r\n")
    winstr199 = (winstr + "99\r\n")

    file = open("wordlist_test.txt", "a")
    file.write(wordinputstr + " \n ")
    file.close()

    # writing variations of string to list
    file = open("wordlist_test.txt", "a")
    file.write(winstr53)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr54)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr55)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr56)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr57)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr58)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr59)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr60)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr61)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr61)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr62)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr63)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr64)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr65)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr66)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr67)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr68)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr69)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr70)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr71)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr72)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr73)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr74)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr75)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr76)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr77)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr78)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr79)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr80)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr81)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr82)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr83)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr84)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr85)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr86)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr87)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr88)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr89)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr90)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr91)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr92)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr93)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr94)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr95)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr96)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr97)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr98)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr99)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr153)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr154)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr155)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr156)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr157)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr158)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr159)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr160)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr161)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr161)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr162)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr163)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr164)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr165)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr166)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr167)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr168)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr169)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr170)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr171)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr172)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr173)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr174)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr175)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr176)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr177)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr178)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr179)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr180)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr181)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr182)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr183)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr184)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr185)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr186)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr187)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr188)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr189)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr190)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr191)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr192)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr193)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr194)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr195)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr196)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr197)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr198)
    file.close()
    file = open("wordlist_test.txt", "a")
    file.write(winstr199)
    file.close()

    os.system('cls')
    print("Word added to list. Type '1' to continue or '2' to stop.")
    choice=input("")
    if choice == "1":
        listappend()
    if choice == "2":
        main()

def addbasics():
    file = open("wordlist_test.txt", "w+")
    file.write("password \r\n 123456 \r\n 12345678 \r\n 1234 \r\n qwerty \r\n 12345 \r\n dragon \r\n pussy \r\n baseball \r\n football \r\n letmein \r\n monkey \r\n 696969 \r\n abc123 \r\n mustang \r\n michael \r\n shadow \r\n master \r\n jennifer \r\n 111111 \r\n 2000")
    file.write("\r\n jordan \r\n superman \r\n harley \r\n 1234567 \r\n fuckme \r\n hunter \r\n fuckyou \r\n trustno1 \r\n ranger \r\n buster \r\n thomas \r\n tigger \r\n robert \r\n soccer \r\n fuck \r\n batman \r\n test \r\n pass \r\n killer \r\n hockey \r\n george \r\n charlie \r\n andrew")
    file.write("\r\n michelle \r\n love \r\n sunshine \r\n jessica \r\n asshole \r\n 6969 \r\n pepper \r\n daniel \r\n access \r\n 123456789 \r\n 654321 \r\n joshua \r\n maggie \r\n starwars \r\n silver \r\n william \r\n dallas \r\n yankees \r\n ")
    file.write(" \r\n 123123 \r\nashley \r\n 666666 \r\n hello \r\n amanda \r\n orange \r\n biteme \r\n freedom \r\n computer \r\n sexy \r\n thunder \r\n nicole \r\n ginger \r\n heather \r\n")
    file.write(" \r\n heather \r\n hammer \r\n summer \r\n corvette \r\n taylor \r\n fucker \r\n austin \r\n 1111 \r\n merlin \r\n matthew \r\n 121212 \r\n golfer \r\n cheese \r\n princess \r\n martin \r\n chelsea \r\n patrick \r\n richard \r\n diamond \r\n yellow \r\n bigdog \r\n secret \r\nasdfgh \r\n sparky \r\n cowboy")
    file.close()
    print("")
    print("Boom! That's a lot of words.")
    main()

main()

